dimmable_monitors:
- "CTZFF83"
- "CLRKF83"
dimm_brightness_off: 100
dimm_brightness_on: 20
kb_languague_switch: True
games_to_dimm:
- "Counter-Strike: Global Offensive - Direct3D 9"
- "League of Legends (TM) Client"
- "League of Legends"
- "EscapeFromTarkov"
